# Generated by Django 3.1.5 on 2021-01-30 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Eq_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eq_model', models.CharField(blank=True, default='Unnamed', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='Unnamed', max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Eq_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eq_type', models.CharField(blank=True, default='Unnamed', max_length=30)),
                ('eq_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.eq_model')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.manufacturer')),
            ],
        ),
        migrations.AddField(
            model_name='eq_model',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.manufacturer'),
        ),
        migrations.CreateModel(
            name='Eq_mark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eq_mark', models.CharField(blank=True, default='Unnamed', max_length=60)),
                ('h_curve_points', models.CharField(blank=True, default='0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00', max_length=150)),
                ('q_curve_points', models.CharField(blank=True, default='0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00', max_length=150)),
                ('p2_curve_points', models.CharField(blank=True, default='0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00', max_length=150)),
                ('npsh_curve_points', models.CharField(blank=True, default='0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00', max_length=150)),
                ('efficiency_curve_points', models.CharField(blank=True, default='0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00', max_length=150)),
                ('eq_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.eq_model')),
                ('eq_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.eq_type')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.manufacturer')),
            ],
        ),
    ]
