# Generated by Django 3.1.5 on 2021-01-30 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EqModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eqmodel', models.CharField(blank=True, default='Unnamed', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='Unnamed', max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='EqType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eqtype', models.CharField(blank=True, default='Unnamed', max_length=30)),
                ('eqmodel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.eqmodel')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.manufacturer')),
            ],
        ),
        migrations.AddField(
            model_name='eqmodel',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.manufacturer'),
        ),
        migrations.CreateModel(
            name='EqMark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eqmark', models.CharField(blank=True, default='Unnamed', max_length=60)),
                ('h_curve_points', models.CharField(blank=True, default='0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00', max_length=150)),
                ('q_curve_points', models.CharField(blank=True, default='0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00', max_length=150)),
                ('p2_curve_points', models.CharField(blank=True, default='0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00', max_length=150)),
                ('npsh_curve_points', models.CharField(blank=True, default='0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00', max_length=150)),
                ('efficiency_curve_points', models.CharField(blank=True, default='0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00', max_length=150)),
                ('eqmodel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.eqmodel')),
                ('eqtype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.eqtype')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.manufacturer')),
            ],
        ),
    ]
