# Generated by Django 3.1.5 on 2021-03-01 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eqmark',
            name='cost',
            field=models.CharField(default='not_specified', max_length=10),
        ),
        migrations.AddField(
            model_name='eqmark',
            name='dn',
            field=models.CharField(default='not_specified', max_length=10),
        ),
        migrations.AddField(
            model_name='eqmark',
            name='q_optimal',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='eqmark',
            name='speed',
            field=models.CharField(default='not_specified', max_length=10),
        ),
    ]
