# Generated by Django 3.1.5 on 2021-03-20 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_eqmark_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='eqmark',
            name='size',
            field=models.CharField(default='-', max_length=16),
        ),
    ]
